[build]
    command = "yarn build"
    publish="./build"
    base = ""

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200


[build.environment]
  NODE_VERSION = "14.18.0"
  YARN_VERSION = "1.22.17"
  NPM_VERSION = "8.5.4"